# Generated by Django 5.0.2 on 2024-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=80)),
                ('zona', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bodegueador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cantidad_resenas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=40)),
                ('bodegon', models.CharField(max_length=40)),
                ('fecha', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=1500)),
            ],
        ),
    ]
