# Generated by Django 5.0.2 on 2024-03-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='fecha',
            field=models.DateField(),
        ),
    ]
