# Generated by Django 4.2.5 on 2024-03-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0002_alter_resena_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodegon',
            options={'verbose_name': 'Bodegon', 'verbose_name_plural': 'Bodegones'},
        ),
        migrations.AlterModelOptions(
            name='bodegueador',
            options={'verbose_name': 'Bodegueador', 'verbose_name_plural': 'Bodegueadores'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
